export default [
    "Inglaterra",
    "Austria",
    "Noruega",
    "Irlanda del Norte",
    "Alemania",
    "Dinamarca",
    "España",
    "Finlandia",
    "Países Bajos",
    "Suecia",
    "Portugal",
    "Suiza",
    "Francia",
    "Italia",
    "Bélgica",
    "Islandia",]